In [1]:
import pandas as pd
import numpy as np

### Import the .csv file ###

In [2]:
df = pd.read_csv('customer_support_tickets_2.csv')
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,22-03-2021,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,01-06-2023 12:15,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,22-05-2021,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,01-06-2023 16:45,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,14-07-2020,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,01-06-2023 11:14,01-06-2023 18:05,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,13-11-2020,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,01-06-2023 07:29,01-06-2023 01:57,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,04-02-2020,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,01-06-2023 00:12,01-06-2023 19:53,1.0

In [3]:
df_cpy1 = df.copy()
df_cpy1.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,22-03-2021,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,01-06-2023 12:15,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,22-05-2021,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,01-06-2023 16:45,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,14-07-2020,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,01-06-2023 11:14,01-06-2023 18:05,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,13-11-2020,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,01-06-2023 07:29,01-06-2023 01:57,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,04-02-2020,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,01-06-2023 00:12,01-06-2023 19:53,1.0

### STEP 1 — Basic Inspection ###

In [4]:
df_cpy1.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   str
 2   Customer Email                8469 non-null   str
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   str
 5   Product Purchased             8469 non-null   str
 6   Date of Purchase              8469 non-null   str
 7   Ticket Type                   8469 non-null   str
 8   Ticket Subject                8469 non-null   str
 9   Ticket Description            8469 non-null   str
 10  Ticket Status                 8469 non-null   str
 11  Resolution                    2769 non-null   str
 12  Ticket Priority               8469 non-null   str
 13  Ticket Channel                8469 non-null   str
 14  First Response Time           5650 non-null   str
 15  Time to Resolution            2769 non-null   str
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), str(14)
memory usage: 1.1 MB

In [5]:
df_cpy1.describe()

         Ticket ID  Customer Age  Customer Satisfaction Rating
count  8469.000000   8469.000000                   2769.000000
mean   4235.000000     44.026804                      2.991333
std    2444.934048     15.296112                      1.407016
min       1.000000     18.000000                      1.000000
25%    2118.000000     31.000000                      2.000000
50%    4235.000000     44.000000                      3.000000
75%    6352.000000     57.000000                      4.000000
max    8469.000000     70.000000                      5.000000

In [6]:
df_cpy1.isnull().sum()

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

### STEP 2 — Check Duplicates ###

In [7]:
df_cpy1.duplicated().sum()

np.int64(0)

### STEP 3 — Standardize Column Names ###

In [8]:
df_cpy1.columns = df_cpy1.columns.str.lower().str.replace(" ","_")

In [9]:
df_cpy1.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'customer_age',
       'customer_gender', 'product_purchased', 'date_of_purchase',
       'ticket_type', 'ticket_subject', 'ticket_description', 'ticket_status',
       'resolution', 'ticket_priority', 'ticket_channel',
       'first_response_time', 'time_to_resolution',
       'customer_satisfaction_rating'],
      dtype='str')

### STEP 4 — Date Formatting ###

In [11]:
df_cpy1['date_of_purchase'].dtype

In [12]:
df_cpy1['date_of_purchase'] = pd.to_datetime(df_cpy1['date_of_purchase'], format='mixed', errors = 'coerce')

In [13]:
df_cpy1['date_of_purchase'].dtype

dtype('<M8[us]')

In [14]:
df_cpy1['first_response_time'].dtype

In [15]:
df_cpy1['first_response_time'] = pd.to_datetime(df_cpy1['first_response_time'],format='mixed',errors='coerce')

In [16]:
df_cpy1['first_response_time'].dtype

dtype('<M8[us]')

In [17]:
df_cpy1['time_to_resolution'].dtype

In [18]:
df_cpy1['time_to_resolution'] = pd.to_datetime(df_cpy1['time_to_resolution'], format='mixed', errors='coerce')
df_cpy1['time_to_resolution'].dtype
print("df_cpy1['time_to_resolution'] --> datatype has been changed")

df_cpy1['time_to_resolution'] --> datatype has been changed

### STEP 5 — Check Missing Values ###

In [19]:
df_cpy1.isnull().sum()

ticket_id                          0
customer_name                      0
customer_email                     0
customer_age                       0
customer_gender                    0
product_purchased                  0
date_of_purchase                   0
ticket_type                        0
ticket_subject                     0
ticket_description                 0
ticket_status                      0
resolution                      5700
ticket_priority                    0
ticket_channel                     0
first_response_time             2819
time_to_resolution              5700
customer_satisfaction_rating    5700
dtype: int64

In [20]:
df_cpy1.head()

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,ticket_status,resolution,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-01-06 12:15:00,NaT,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-01-06 16:45:00,NaT,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-01-06 11:14:00,2023-01-06 18:05:00,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-01-06 07:29:00,2023-01-06 01:57:00,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-04-02,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-01-06 00:12:00,2023-01-06 19:53:00,1.0

In [21]:
df_cpy1['resolution'] = df_cpy1['resolution'].fillna('Unknown')
print("Handled NaN in resolutions")

Handled NaN in resolutions

In [22]:
df_cpy1['customer_satisfaction_rating'] = df_cpy1['customer_satisfaction_rating'].fillna('Unknown')

In [23]:
df_cpy1.head()

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,ticket_status,resolution,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,Unknown,Critical,Social media,2023-01-06 12:15:00,NaT,Unknown
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,Unknown,Critical,Chat,2023-01-06 16:45:00,NaT,Unknown
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-01-06 11:14:00,2023-01-06 18:05:00,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-01-06 07:29:00,2023-01-06 01:57:00,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-04-02,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-01-06 00:12:00,2023-01-06 19:53:00,1.0

### STEP 6 — Standardize Categories ###

In [24]:
df_cpy1['ticket_priority'].unique()

<StringArray>
['Critical', 'Low', 'High', 'Medium']
Length: 4, dtype: str

In [25]:
df_cpy1['ticket_priority'] = df_cpy1['ticket_priority'].str.strip()

### STEP 7 - Final checkup before exporting ###

In [26]:
df_cpy1.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ticket_id                     8469 non-null   int64
 1   customer_name                 8469 non-null   str
 2   customer_email                8469 non-null   str
 3   customer_age                  8469 non-null   int64
 4   customer_gender               8469 non-null   str
 5   product_purchased             8469 non-null   str
 6   date_of_purchase              8469 non-null   datetime64[us]
 7   ticket_type                   8469 non-null   str
 8   ticket_subject                8469 non-null   str
 9   ticket_description            8469 non-null   str
 10  ticket_status                 8469 non-null   str
 11  resolution                    8469 non-null   str
 12  ticket_priority               8469 non-null   str
 13  ticket_channel                8469 non-null   str
 14  first_response_time           5650 non-null   datetime64[us]
 15  time_to_resolution            2769 non-null   datetime64[us]
 16  customer_satisfaction_rating  8469 non-null   object
dtypes: datetime64[us](3), int64(2), object(1), str(11)
memory usage: 1.1+ MB

In [27]:
df_cpy1['first_response_time'] = df_cpy1['first_response_time'].fillna('Unknown')

In [28]:
df_cpy1['time_to_resolution'] = df_cpy1['time_to_resolution'].fillna('Unknown')

In [29]:
df_cpy1.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ticket_id                     8469 non-null   int64
 1   customer_name                 8469 non-null   str
 2   customer_email                8469 non-null   str
 3   customer_age                  8469 non-null   int64
 4   customer_gender               8469 non-null   str
 5   product_purchased             8469 non-null   str
 6   date_of_purchase              8469 non-null   datetime64[us]
 7   ticket_type                   8469 non-null   str
 8   ticket_subject                8469 non-null   str
 9   ticket_description            8469 non-null   str
 10  ticket_status                 8469 non-null   str
 11  resolution                    8469 non-null   str
 12  ticket_priority               8469 non-null   str
 13  ticket_channel                8469 non-null   str
 14  first_response_time           8469 non-null   object
 15  time_to_resolution            8469 non-null   object
 16  customer_satisfaction_rating  8469 non-null   object
dtypes: datetime64[us](1), int64(2), object(3), str(11)
memory usage: 1.1+ MB

In [30]:
df_cpy1.duplicated().sum()

np.int64(0)

In [34]:
# df_cpy1['time_to_resolution'] = pd.to_datetime(df_cpy1['time_to_resolution'], format='mixed',)
df_cpy2 = df_cpy1.copy()

In [35]:
df_cpy2['time_to_resolution'] = pd.to_datetime(df_cpy2['time_to_resolution'], format='mixed',errors='coerce')

In [36]:
df_cpy2['time_to_resolution'].dtype

dtype('<M8[us]')

In [37]:
df_cpy1['time_to_resolution'] = pd.to_datetime(df_cpy1['time_to_resolution'], format='mixed',errors='coerce')

In [38]:
df_cpy1['first_response_time'] = pd.to_datetime(df_cpy1['first_response_time'], format='mixed',errors='coerce')

In [39]:
df_cpy1['first_response_time'].dtype

dtype('<M8[us]')

In [40]:
df_cpy1['time_to_resolution'].dtype

dtype('<M8[us]')

In [41]:
df_cpy1['customer_satisfaction_rating'] = pd.to_numeric(df_cpy1['customer_satisfaction_rating'], errors='coerce')

In [42]:
df_cpy1['customer_satisfaction_rating'].dtype

dtype('float64')

In [31]:
df_cpy1.isnull().sum()

ticket_id                       0
customer_name                   0
customer_email                  0
customer_age                    0
customer_gender                 0
product_purchased               0
date_of_purchase                0
ticket_type                     0
ticket_subject                  0
ticket_description              0
ticket_status                   0
resolution                      0
ticket_priority                 0
ticket_channel                  0
first_response_time             0
time_to_resolution              0
customer_satisfaction_rating    0
dtype: int64

### STEP 8 — Export Clean Dataset ###

In [43]:
df_cpy1.to_csv('clean_customer_support_tickets.csv', index=False)
print("Cleaned .csv has been exported")

Cleaned .csv has been exported

In [44]:
df_cpy1.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ticket_id                     8469 non-null   int64
 1   customer_name                 8469 non-null   str
 2   customer_email                8469 non-null   str
 3   customer_age                  8469 non-null   int64
 4   customer_gender               8469 non-null   str
 5   product_purchased             8469 non-null   str
 6   date_of_purchase              8469 non-null   datetime64[us]
 7   ticket_type                   8469 non-null   str
 8   ticket_subject                8469 non-null   str
 9   ticket_description            8469 non-null   str
 10  ticket_status                 8469 non-null   str
 11  resolution                    8469 non-null   str
 12  ticket_priority               8469 non-null   str
 13  ticket_channel                8469 non-null   str
 14  first_response_time           5650 non-null   datetime64[us]
 15  time_to_resolution            2769 non-null   datetime64[us]
 16  customer_satisfaction_rating  2769 non-null   float64
dtypes: datetime64[us](3), float64(1), int64(2), str(11)
memory usage: 1.1 MB

In [45]:
df_cpy1.isnull().sum()

ticket_id                          0
customer_name                      0
customer_email                     0
customer_age                       0
customer_gender                    0
product_purchased                  0
date_of_purchase                   0
ticket_type                        0
ticket_subject                     0
ticket_description                 0
ticket_status                      0
resolution                         0
ticket_priority                    0
ticket_channel                     0
first_response_time             2819
time_to_resolution              5700
customer_satisfaction_rating    5700
dtype: int64

## BUSINESS ANALYSTICS ##

### Create Resolution Duration Metric ###

In [46]:
df_cpy1['resolution_time_hours'] = (df_cpy1['time_to_resolution']-df_cpy1['first_response_time']).dt.total_seconds()/3600

In [47]:
df_cpy1.head()

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,ticket_status,resolution,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating,resolution_time_hours
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,Unknown,Critical,Social media,2023-01-06 12:15:00,NaT,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,Unknown,Critical,Chat,2023-01-06 16:45:00,NaT,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-01-06 11:14:00,2023-01-06 18:05:00,3.0,6.850000
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-01-06 07:29:00,2023-01-06 01:57:00,3.0,-5.533333
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-04-02,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-01-06 00:12:00,2023-01-06 19:53:00,1.0,19.683333

In [48]:
df_cpy1[df_cpy1['resolution_time_hours']<0]

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,ticket_status,resolution,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating,resolution_time_hours
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-01-06 07:29:00,2023-01-06 01:57:00,3.0,-5.533333
11,12,Brandon Arnold,davisjohn@example.net,51,Male,Microsoft Xbox Controller,2021-10-24,Product inquiry,Software bug,I'm having an issue with the {product_purchase...,Closed,Measure there house management pick knowledge ...,High,Chat,2023-01-06 12:05:00,2023-01-06 09:27:00,1.0,-2.633333
16,17,Julia Salazar,watkinsbarbara@example.com,63,Other,Xbox,2021-10-13,Product inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Seek evidence book collection catch.,Critical,Chat,2023-01-06 19:46:00,2023-01-06 15:58:00,4.0,-3.800000
28,29,Christine Wang,garciastacy@example.com,30,Other,Fitbit Charge,2020-10-06,Technical issue,Product recommendation,I'm having an issue with the {product_purchase...,Closed,Soldier we such inside.,Critical,Phone,2023-05-31 23:17:00,2023-01-06 06:03:00,5.0,-3497.233333
35,36,Joann King,jessica10@example.org,24,Other,GoPro Hero,2020-10-13,Cancellation request,Product recommendation,"I've recently set up my {product_purchased}, b...",Closed,Reach paper ability effort learn.,High,Chat,2023-01-06 07:56:00,2023-01-06 00:14:00,1.0,-7.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8452,8453,Craig Forbes,jessica60@example.org,62,Female,MacBook Pro,2020-03-29,Refund request,Display issue,I'm having an issue with the {product_purchase...,Closed,Interesting show must successful.,Critical,Phone,2023-01-06 14:14:00,2023-01-06 05:47:00,3.0,-8.450000
8453,8454,Paula Vazquez,wanderson@example.com,61,Other,iPhone,2020-06-20,Billing inquiry,Peripheral compatibility,The {product_purchased} is unable to establish...,Closed,Skill expect admit and.,High,Chat,2023-01-06 12:56:00,2023-01-06 04:45:00,5.0,-8.183333
8455,8456,Ariel Lee,thompsonsamuel@example.org,54,Other,Dyson Vacuum Cleaner,2021-02-02,Billing inquiry,Refund request,"I've recently set up my {product_purchased}, b...",Closed,Say position key appear behavior.,High,Email,2023-01-06 14:15:00,2023-01-06 06:58:00,1.0,-7.283333
8466,8467,Michelle Kelley,ashley83@example.org,57,Female,GoPro Action Camera,2021-08-17,Technical issue,Account access,I'm having an issue with the {product_purchase...,Closed,Eight account century nature kitchen.,High,Social media,2023-01-06 09:44:00,2023-01-06 04:31:00,3.0,-5.216667
8467,8468,Steven Rodriguez,fpowell@example.org,54,Male,PlayStation,2021-10-16,Product inquiry,Payment issue,I'm having an issue with the {product_purchase...,Closed,We seat culture plan.,Medium,Email,2023-01-06 18:28:00,2023-01-06 05:32:00,3.0,-12.933333

In [53]:
negetive_df_cpy1 = df_cpy1[df_cpy1['resolution_time_hours']<0]

negetive_df_cpy1[
    ['ticket_id','first_response_time','time_to_resolution','ticket_status']
].head(20)

     ticket_id first_response_time  time_to_resolution ticket_status
3            4 2023-01-06 07:29:00 2023-01-06 01:57:00        Closed
11          12 2023-01-06 12:05:00 2023-01-06 09:27:00        Closed
16          17 2023-01-06 19:46:00 2023-01-06 15:58:00        Closed
28          29 2023-05-31 23:17:00 2023-01-06 06:03:00        Closed
35          36 2023-01-06 07:56:00 2023-01-06 00:14:00        Closed
41          42 2023-01-06 20:25:00 2023-01-06 14:43:00        Closed
44          45 2023-01-06 05:58:00 2023-01-06 03:19:00        Closed
47          48 2023-01-06 07:16:00 2023-01-06 05:59:00        Closed
51          52 2023-01-06 16:21:00 2023-01-06 10:31:00        Closed
58          59 2023-01-06 11:56:00 2023-01-06 04:45:00        Closed
59          60 2023-01-06 19:50:00 2023-01-06 00:38:00        Closed
62          63 2023-05-31 23:37:00 2023-01-06 12:41:00        Closed
72          73 2023-01-06 04:35:00 2023-01-06 03:17:00        Closed
73          74 2023-01-06 21:31:00 2023-01-06 02:24:00        Closed
75          76 2023-01-06 14:43:00 2023-01-06 02:30:00        Closed
77          78 2023-01-06 19:16:00 2023-01-06 15:21:00        Closed
86          87 2023-01-06 18:03:00 2023-01-06 06:23:00        Closed
89          90 2023-05-31 23:17:00 2023-01-06 03:09:00        Closed
114        115 2023-01-06 10:27:00 2023-01-06 06:04:00        Closed
116        117 2023-01-06 19:02:00 2023-01-06 18:17:00        Closed

In [50]:
negetive_df_cpy1

['ticket_id', 'first_response_time', 'time_to_resolution', 'ticket_status']

### Create Data Quality Flag ###

In [54]:
df_cpy1['data_quality_flag'] = df_cpy1['resolution_time_hours'].apply(
    lambda x:'Invalid Duration'
    if pd.notnull(x) and x<0
    else 'Valid'
)

In [55]:
df_cpy1.head()

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,ticket_status,resolution,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating,resolution_time_hours,data_quality_flag
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,Unknown,Critical,Social media,2023-01-06 12:15:00,NaT,NaN,NaN,Valid
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,Unknown,Critical,Chat,2023-01-06 16:45:00,NaT,NaN,NaN,Valid
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-01-06 11:14:00,2023-01-06 18:05:00,3.0,6.850000,Valid
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-01-06 07:29:00,2023-01-06 01:57:00,3.0,-5.533333,Invalid Duration
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-04-02,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-01-06 00:12:00,2023-01-06 19:53:00,1.0,19.683333,Valid

### Create Clean Resolution Metric ###

In [56]:
df_cpy1.loc[df_cpy1['resolution_time_hours']<0,'resolution_time_hours'] = None

In [57]:
df_cpy1.head()

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,ticket_status,resolution,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating,resolution_time_hours,data_quality_flag
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,Unknown,Critical,Social media,2023-01-06 12:15:00,NaT,NaN,NaN,Valid
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,Unknown,Critical,Chat,2023-01-06 16:45:00,NaT,NaN,NaN,Valid
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-01-06 11:14:00,2023-01-06 18:05:00,3.0,6.850000,Valid
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-01-06 07:29:00,2023-01-06 01:57:00,3.0,NaN,Invalid Duration
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-04-02,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-01-06 00:12:00,2023-01-06 19:53:00,1.0,19.683333,Valid

In [58]:
df_cpy1.isnull().sum()

ticket_id                          0
customer_name                      0
customer_email                     0
customer_age                       0
customer_gender                    0
product_purchased                  0
date_of_purchase                   0
ticket_type                        0
ticket_subject                     0
ticket_description                 0
ticket_status                      0
resolution                         0
ticket_priority                    0
ticket_channel                     0
first_response_time             2819
time_to_resolution              5700
customer_satisfaction_rating    5700
resolution_time_hours           7046
data_quality_flag                  0
dtype: int64

In [59]:
df_cpy1.to_csv('cleaning_customer_support_tickets_v2.csv',index=False)

### Import to SQL ###

In [60]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:root@localhost:5432/ecomm_analysis')

print("Engine running")

Engine running

In [61]:
df_cpy1.to_sql('support_tickets',engine,if_exists='replace',index=False)

469